#!/usr/bin/env bash
case "${1:-}" in
    services.ollama.enable) value=true ;;
    services.ollama.openFirewall) value=false ;;
    *) exit 1 ;;
esac
printf '%s\n' 'Value:' "  $value" '' 'Default:' '  false' '' 'Type:' '  boolean'
